version: 2
updates:
  # Maintain dependencies for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  # Maintain dependencies for the React Client (Frontend)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(client):"

  # Maintain dependencies for the Node Server (Backend)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(server):"
