services:
  shopsmart-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopsmart-app
    ports:
      - '5005:5005'
    environment:
      - PORT=5005
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password123@shopsmart-db:5432/shopsmart
    depends_on:
      - shopsmart-db
    restart: unless-stopped

  shopsmart-db:
    image: postgres:16-alpine
    container_name: shopsmart-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=shopsmart
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
